\documentclass{../../slides-style}

\slidetitle{Исключения и обработка ошибок}{18.03.2025}

\begin{document}
    
    \begin{frame}[plain]
        \titlepage
    \end{frame}

    \section{Data-driven testing}

    \begin{frame}[fragile]
        \frametitle{TestCaseData (NUnit)}
        \begin{minted}{csharp}
public class StackTest
{
    [TestCaseSource(nameof(Stacks))]
    public void StackShouldNotEmptyAfterPush(IStack stack)
    {
        stack.Push(1);
        Assert.IsFalse(stack.IsEmpty());
    }

    private static IEnumerable<TestCaseData> Stacks
        => new TestCaseData[]
        {
            new TestCaseData(new ArrayStack()),
            new TestCaseData(new ListStack()),
        };
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Ещё хороший приём}
        \begin{minted}{csharp}
private static IEnumerable<TestCaseData> Stacks { 
    get {
        var stacks = new List<IStack>() 
            { new ArrayStack(), new ListStack() };
        var data = new List<int>() { 1, 2, 3 };
        var result = new List<TestCaseData>();
        foreach (var stack in stacks) {
            foreach (var item in data) {
                result.Add(new TestCaseData(item, stack));
            }
        }
        return result;
    }
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Более простые случаи}
        \begin{minted}{csharp}
[TestCase(12, 3, 4)]
[TestCase(12, 2, 6)]
public void DivideTest(int n, int d, int q)
{
    Assert.AreEqual(q, n / d);
}
        \end{minted}
        \vspace{3mm}
        Или даже
        \begin{minted}{csharp}
[TestCase(12, 3, ExpectedResult=4)]
[TestCase(12, 2, ExpectedResult=6)]
public int DivideTest(int n, int d)
{
    return n / d;
}
        \end{minted}
    \end{frame}

    \section{Исключения}

    \begin{frame}[fragile]
        \frametitle{Бросание исключений}
        \begin{minted}{csharp}
if (t == null)
{
    throw new NullReferenceException();
}

throw new NullReferenceException("Hello!");
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Обработка исключений}
        \begin{minted}{csharp}
try {
    // Код, который может бросать исключения
} catch (Type1 id1) {
    // Обработка исключений типа Type1
} catch (Type2 id2) {
    // Обработка исключений типа Type2
} catch {
    // Обработка всех оставшихся исключений
} finally {
    // Код, выполняющийся в любом случае
}
        \end{minted}
    \end{frame}

    \begin{frame}
        \frametitle{Что делается}
        \begin{itemize}
            \item На куче создаётся объект-исключение
            \item Исполнение метода прерывается
            \item Если в вызывающем методе есть обработчик этого исключения, вызывается он, иначе исполнение вызывающего тоже прерывается
            \item И т.д., пока не найдём обработчик или прервём Main
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Пример}
        \begin{small}
            \begin{minted}{csharp}
private void ReadData(String pathName) 
{
    FileStream fs = null;
    try {
        fs = new FileStream(pathName, FileMode.Open);
        // Делать что-то полезное
    }
    catch (IOException) {
        // Код восстановления после ошибки
    }
    finally {
        // Закрыть файл надо в любом случае
        if (fs != null) 
        {
            fs.Close();
        }
    }
}
            \end{minted}
        \end{small}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Фильтры исключений}
        \begin{small}
            \begin{minted}{csharp}
public static string MakeRequest()
{
    try
    {
        var request = WebRequest.Create("http://se.math.spbu.ru");
        var response = request.GetResponse();
        var stream = response.GetResponseStream();
        var reader = new StreamReader(stream);
        var data = reader.ReadToEnd();
        return data;
    }
    catch (WebException e) 
        when (e.Status == WebExceptionStatus.ConnectFailure)
    {
        return "Connection failed";
    }
}
            \end{minted}
        \end{small}
    \end{frame}

    \begin{frame}
        \frametitle{Иерархия классов-исключений}
        \begin{tiny}
            \begin{forest}
                for tree={rectangle,draw,l sep=1cm,s sep=3mm,edge=open triangle 60-}
                [Object
                    [Exception
                        [SystemException
                            [IndexOutOfRangeException]
                            [NullReferenceException]
                            [StackOverflowException]
                            [ArgumentException
                                [ArgumentNullException]
                                [ArgumentOutOfRangeException]
                                [\dots]
                            ]
                        ]
                        [ApplicationException]
                    ]
                ]
            \end{forest}
        \end{tiny}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Свойства класса Exception}
        \begin{itemize}
            \item Data
            \item HelpLink
            \item InnerException
            \item Message
            \item Source
            \item StackTrace
            \item HResult
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Пример (плохой)}
        \begin{minted}{csharp}
try
{
    throw new Exception("Something is very wrong");
}
catch (Exception e)
{
    Console.WriteLine("Caught Exception");
    Console.WriteLine("e.Message: " + e.Message);
    Console.WriteLine("e.ToString(): " + e.ToString());
    Console.WriteLine("e.StackTrace:\n" + e.StackTrace);
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Что выведется}
        \begin{scriptsize}
            \begin{minted}{csharp}
Caught Exception
e.Message: Something is very wrong
e.ToString(): System.Exception: Something is very wrong
   в CSharpConsoleApplication.Program.Main(String[] args) в 
       c:\Projects\CSharpConsoleApplication\CSharpConsoleApplication\Program.cs: строка 15
e.StackTrace:
   в CSharpConsoleApplication.Program.Main(String[] args) в 
       c:\Projects\CSharpConsoleApplication\CSharpConsoleApplication\Program.cs:строка 15
Для продолжения нажмите любую клавишу . . .
            \end{minted}
        \end{scriptsize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Перебрасывание исключений}
        \begin{minted}{csharp}
try
{
    throw new Exception("Something is wrong");
}
catch (Exception e)
{
    Console.WriteLine("Caught Exception");
    throw;  // "throw e;" тоже работает, но сбросит stack trace
}
        \end{minted}

        Или
        \begin{minted}{csharp}
throw new Exception("Outer exception", e);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Свои классы-исключения}
        \begin{minted}{csharp}
public class MyException : Exception
{
    public MyException() 
    {
    }

    public MyException(string message)
        : base(message)
    {
    }
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Идеологически правильное объявление исключения}
        \begin{minted}{csharp}
[Serializable]
public class MyException : Exception
{
    public MyException() { }
    public MyException(string message) : base(message) { }
    public MyException(string message, Exception inner) 
        : base(message, inner) { }
    protected MyException(
        System.Runtime.Serialization.SerializationInfo info,
        System.Runtime.Serialization.StreamingContext context)
            : base(info, context) { }
}
        \end{minted}
    \end{frame}

    \begin{frame}
        \frametitle{``Интересные'' классы-исключения}
        \begin{itemize}
            \item Corrupted state exceptions (CSE) --- не ловятся catch-ем
            \begin{itemize}
                \item StackOverflowException
                \item AccessViolationException
                \item System.Runtime.InteropServices.SEHException
            \end{itemize}
            \item FileLoadException, BadImageFormatException, InvalidProgramException, ...
            \item ThreadAbortException
            \item TypeInitializationException
            \item TargetInvocationException
            \item OutOfMemoryException
            \item Можно кидать null. При этом рантайм сам кидает NullReferenceException.
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Environment.FailFast}
        \begin{minted}{csharp}
try 
{
     // Делать что-то полезное
}
catch (OutOfMemoryException e) 
{
    Console.WriteLine("Закончилась память :(");
    Environment.FailFast(
        String.Format($"Out of Memory: {e.Message}"));
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Исключения и тесты}
        \begin{footnotesize}
            \begin{minted}{csharp}
[TestMethod]
[ExpectedException(typeof(DivideByZeroException))]
public void DivideTest()
{
    var target = new DivisionClass();
    int numerator = 4;
    int denominator = 0;
    int actual = target.Divide(numerator, denominator);
}
            \end{minted}
        \end{footnotesize}
        или (более правильно)
        \begin{footnotesize}
            \begin{minted}{csharp}
[TestMethod]
public void DivideTest()
{
    var target = new DivisionClass();
    int numerator = 4;
    int denominator = 0;
    Assert.Throws<DivideByZeroException>(() => target.Divide(numerator, denominator));
}
            \end{minted}
        \end{footnotesize}
    \end{frame}

    \begin{frame}
        \frametitle{Исключения, best practices}
        \begin{itemize}
            \item Не бросать исключения без нужды
            \begin{itemize}
                \item В нормальном режиме работы исключения бросаться не должны вообще
            \end{itemize}
            \item Свои исключения наследовать от System.Exception
            \item Документировать все свои исключения, бросаемые методом
            \item Не ловить Exception, SystemException
            \begin{itemize}
                \item Исключения, указывающие на ошибку в коде (например, NullReferenceException) уж точно не ловить
            \end{itemize}
            \item По возможности кидать библиотечные исключения или их наследников:
            \begin{itemize}
                \item InvalidOperationException
                \item ArgumentException
            \end{itemize}
            \item Имя класса должно заканчиваться на ``Exception''
            \item Код должен быть безопасным с точки зрения исключений
            \begin{itemize}
                \item Не забывать про finally 
                \item Или using, lock, foreach, которые тоже генерят finally
            \end{itemize}
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{using, IDisposable}
        \begin{small}
            \begin{minted}{csharp}
public static class Program {
    public static void Main() {
        var bytesToWrite = new Byte[] { 1, 2, 3, 4, 5 };
        using (var fs = new FileStream("Temp.dat", FileMode.Create)) {
            fs.Write(bytesToWrite, 0, bytesToWrite.Length);
        }
        File.Delete("Temp.dat");
    }
}
            \end{minted}
        \end{small}
        Если есть хоть одно поле IDisposable, сам класс должен быть IDisposable!
    \end{frame}

    \section{Особенности современного C\#}

    \begin{frame}[fragile]
        \frametitle{Особенности современного C\#}
        \framesubtitle{Кортежи и деконструкция}
        \begin{minted}{csharp}
static (int prev, int cur) Fibonacci(int n)
{
    var (prevPrev, prev) = n <= 2 ? (0, 1) : Fibonacci(n - 1);
    return (prev, prevPrev + prev);
}

var (_, result) = Fibonacci(7);
Console.WriteLine(result);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Именованные поля кортежей}
        \begin{minted}{csharp}
int count = 5;
string label = "Colors used in the map";
var pair = (count: count, label: label);

int count = 5;
string label = "Colors used in the map";
var pair = (count, label);  // имена полей --- "count" и "label"
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Null propagation}
        \begin{minted}{csharp}
var first = person?.FirstName;

int? age = person?.Age;
if (age.HasValue)
{
    int realAge = age.Value;
}


var otherFirst = person?.FirstName ?? "Unspecified";
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Локальные функции}
        \begin{small}
            \begin{minted}{csharp}
public int Fibonacci(int x)
{
    if (x < 0) 
        throw new ArgumentException("Less negativity please!", nameof(x));
    return Fib(x).current;

    (int current, int previous) Fib(int i)
    {
        if (i == 0) return (1, 0);
        var (p, pp) = Fib(i - 1);
        return (p + pp, p);
    }
}
            \end{minted}
        \end{small}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Индексовая инициализация}
        \begin{minted}{csharp}
private Dictionary<int, string> webErrors = new Dictionary<int, string>
{
    [404] = "Page not Found",
    [302] = "Page moved, but left a forwarding address.",
    [500] = "The web server can't come out to play today."
};
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Именованные и необязательные аргументы}
        \begin{minted}{csharp}
PrintOrderDetails(productName: "Red Mug", 31, "Gift Shop");

public void ExampleMethod(int required, 
    string optionalStr = "default string",
    int optionalInt = 10)

anExample.ExampleMethod(3, optionalInt: 4);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{params}
        \begin{minted}{csharp}
public static void UseParams(params int[] list)
{
    for (int i = 0; i < list.Length; i++)
    {
        Console.Write(list[i] + " ");
    }
    Console.WriteLine();
}
...
UseParams(1, 2, 3, 4);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{switch expression}
        \begin{minted}{csharp}
public static RGBColor FromRainbow(Rainbow colorBand) =>
    colorBand switch
    {
        Rainbow.Red    => new RGBColor(0xFF, 0x00, 0x00),
        Rainbow.Orange => new RGBColor(0xFF, 0x7F, 0x00),
        Rainbow.Yellow => new RGBColor(0xFF, 0xFF, 0x00),
        Rainbow.Blue   => new RGBColor(0x00, 0x00, 0xFF),
        Rainbow.Indigo => new RGBColor(0x4B, 0x00, 0x82),
        Rainbow.Violet => new RGBColor(0x94, 0x00, 0xD3),
        _ => throw new ArgumentException(
                message: "invalid enum value", 
                paramName: nameof(colorBand)),
    };
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{switch по свойствам}
        \begin{minted}{csharp}
public static decimal ComputeSalesTax(Address location, 
        decimal salePrice) =>
    location switch
    {
        { State: "WA" } => salePrice * 0.06M,
        { State: "MN" } => salePrice * 0.75M,
        { State: "MI" } => salePrice * 0.05M,
        // ...
        _ => 0M
    };
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{switch по кортежам}
        \begin{minted}{csharp}
public static string RockPaperScissors(string first, string second)
    => (first, second) switch
    {
        ("rock", "paper") => "rock is covered by paper. Paper wins.",
        ("rock", "scissors") => "rock breaks scissors. Rock wins.",
        ("paper", "rock") => "paper covers rock. Paper wins.",
        ("paper", "scissors") => "paper is cut by scissors. Scissors wins.",
        ("scissors", "rock") => "scissors is broken by rock. Rock wins.",
        ("scissors", "paper") => "scissors cuts paper. Scissors wins.",
        (_, _) => "tie"
    };
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Шаблоны в var}
        \begin{minted}{csharp}
var (x, y) = (1, 2);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Deconstruct}
        \begin{minted}{csharp}
public class Point
{
    public int X { get; }
    public int Y { get; }

    public Point(int x, int y) => (X, Y) = (x, y);

    public void Deconstruct(out int x, out int y) =>
        (x, y) = (X, Y);
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{И использование}
        \begin{minted}{csharp}
var point = new Point(10, 20);
var (a, b) = point;
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Позиционные шаблоны}
        \begin{minted}{csharp}
static string Quadrant(Point p) => p switch
{
    (0, 0) => "origin",
    (var x, var y) when x > 0 && y > 0 => "Quadrant 1",
    (var x, var y) when x < 0 && y > 0 => "Quadrant 2",
    (var x, var y) when x < 0 && y < 0 => "Quadrant 3",
    (var x, var y) when x > 0 && y < 0 => "Quadrant 4",
    (var x, var y) => "on a border",
    _ => "unknown"
};
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Продвинутое сопоставление шаблонов}
        \begin{minted}{csharp}
public static bool IsLetterOrSeparator(char c) =>
    c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z') or '.' or ',';

if (e is not null)
{
    // ...
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Record-ы}
        \begin{minted}{csharp}
public class Person
{
    public string LastName { get; }
    public string FirstName { get; }

    public Person(string first, string last) 
        => (FirstName, LastName) = (first, last);
}
        \end{minted}
        vs
        \begin{minted}{csharp}
public record Person(string FirstName, string LastName);
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{C\# 10}
        \begin{itemize}
            \item File-scoped namespaces
            \item global using
            \item Улучшенные шаблоны: \mintinline{csharp}|{ Prop1.Prop2: pattern }|
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{C\# 11}
        \begin{itemize}
            \item Шаблоны для списков: \mintinline{csharp}|sequence is [1, 2, 3]|
            \item Сырые строки:
                \begin{minted}{csharp}
string longMessage = """
    This is a long message.
    It has several lines.
        Some are indented
                more than others.
    Some should start at the first column.
    Some have "quoted text" in them.
    """;
                \end{minted}
                и
                \begin{minted}{csharp}
var location = $$"""
   You are at {{{Longitude}}, {{Latitude}}}
   """;
                \end{minted}
        \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{File-local types}
        \begin{minted}{csharp}
// File1.cs
namespace NS;
file class Widget
{
}

// File2.cs
namespace NS;
file class Widget // Совсем другой Widget
{
}

// File3.cs
using NS;
var widget = new Widget(); // Ошибка
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Основные конструкторы (C\# 12)}
        \begin{minted}{csharp}
public struct Distance(double dx, double dy)
{
    public readonly double Magnitude => Math.Sqrt(dx * dx + dy * dy);
    public readonly double Direction => Math.Atan2(dy, dx);

    public void Translate(double deltaX, double deltaY)
    {
        dx += deltaX;
        dy += deltaY;
    }

    public Distance() : this(0,0) { }
}
        \end{minted}
    \end{frame}

    \begin{frame}[fragile]
        \frametitle{Collection expressions (C\# 12)}
        \begin{minted}{csharp}
int[] row0 = [1, 2, 3];
int[] row1 = [4, 5, 6];
int[] row2 = [7, 8, 9];
int[] single = [.. row0, .. row1, .. row2];
foreach (var element in single)
{
    Console.Write($"{element}, ");
}
// output:
// 1, 2, 3, 4, 5, 6, 7, 8, 9,
        \end{minted}
    \end{frame}

\end{document}